//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.esri.gpt.csw {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.esri.gpt.csw.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://esriurl.com/geoportal.
        /// </summary>
        internal static string aboutUrl {
            get {
                return ResourceManager.GetString("aboutUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstract:.
        /// </summary>
        internal static string abstractLabel {
            get {
                return ResourceManager.GetString("abstractLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add ArcGIS map service layer..
        /// </summary>
        internal static string AddArcGISLayerFailed {
            get {
                return ResourceManager.GetString("AddArcGISLayerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add ArcIMS map service layer..
        /// </summary>
        internal static string AddArcimsLayerFailed {
            get {
                return ResourceManager.GetString("AddArcimsLayerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Map.
        /// </summary>
        internal static string addToMapToolTip {
            get {
                return ResourceManager.GetString("addToMapToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faied to add WMS map service layer..
        /// </summary>
        internal static string AddWmsLayerFailed {
            get {
                return ResourceManager.GetString("AddWmsLayerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSW Client for ArcGIS.
        /// </summary>
        internal static string ApplicationCaption {
            get {
                return ResourceManager.GetString("ApplicationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        internal static string BuildNo {
            get {
                return ResourceManager.GetString("BuildNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog added successfully..
        /// </summary>
        internal static string CatalogAddedSuccessfully {
            get {
                return ResourceManager.GetString("CatalogAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name:.
        /// </summary>
        internal static string catalogDisplayNameLabel {
            get {
                return ResourceManager.GetString("catalogDisplayNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogs.
        /// </summary>
        internal static string catalogListLabel {
            get {
                return ResourceManager.GetString("catalogListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogs.
        /// </summary>
        internal static string CatalogListLabelText {
            get {
                return ResourceManager.GetString("CatalogListLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile:.
        /// </summary>
        internal static string catalogProfileLabel {
            get {
                return ResourceManager.GetString("catalogProfileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data saved..
        /// </summary>
        internal static string CatalogSavedSuccessfully {
            get {
                return ResourceManager.GetString("CatalogSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog Service URL:.
        /// </summary>
        internal static string catalogUrlLabel {
            get {
                return ResourceManager.GetString("catalogUrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All Footprint.
        /// </summary>
        internal static string clearAllFootprintToolTip {
            get {
                return ResourceManager.GetString("clearAllFootprintToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        internal static string configureTabPage {
            get {
                return ResourceManager.GetString("configureTabPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm delete.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to catalog..
        /// </summary>
        internal static string ConnectToCatalogFailed {
            get {
                return ResourceManager.GetString("ConnectToCatalogFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to map service..
        /// </summary>
        internal static string ConnectToMapServiceFailed {
            get {
                return ResourceManager.GetString("ConnectToMapServiceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create WMS group layers..
        /// </summary>
        internal static string CreateWmsGroupLayerFailed {
            get {
                return ResourceManager.GetString("CreateWmsGroupLayerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create WMS layer..
        /// </summary>
        internal static string CreateWmsLayerFailed {
            get {
                return ResourceManager.GetString("CreateWmsLayerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSW catalog is null..
        /// </summary>
        internal static string CswCatalogIsNull {
            get {
                return ResourceManager.GetString("CswCatalogIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSW record is null..
        /// </summary>
        internal static string CswRecordIsNull {
            get {
                return ResourceManager.GetString("CswRecordIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSW Client.
        /// </summary>
        internal static string CswSearchCmdCaption {
            get {
                return ResourceManager.GetString("CswSearchCmdCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geoportal.
        /// </summary>
        internal static string CswSearchCmdCategory {
            get {
                return ResourceManager.GetString("CswSearchCmdCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSW Client.
        /// </summary>
        internal static string CswSearchCmdMessage {
            get {
                return ResourceManager.GetString("CswSearchCmdMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSW Client.
        /// </summary>
        internal static string CswSearchCmdTooltip {
            get {
                return ResourceManager.GetString("CswSearchCmdTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string deleteCatalogToolTip {
            get {
                return ResourceManager.GetString("deleteCatalogToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete?.
        /// </summary>
        internal static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap display_footprint {
            get {
                object obj = ResourceManager.GetObject("display_footprint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Footprint.
        /// </summary>
        internal static string displayFootprintToolTip {
            get {
                return ResourceManager.GetString("displayFootprintToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Metadata.
        /// </summary>
        internal static string DownloadMetadataCaption {
            get {
                return ResourceManager.GetString("DownloadMetadataCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata is empty..
        /// </summary>
        internal static string EmptyMetadata {
            get {
                return ResourceManager.GetString("EmptyMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorMessageDialogCaption {
            get {
                return ResourceManager.GetString("ErrorMessageDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Esri&gt; node missing..
        /// </summary>
        internal static string EsriNodeMissing {
            get {
                return ResourceManager.GetString("EsriNodeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save file..
        /// </summary>
        internal static string FileSaveFailed {
            get {
                return ResourceManager.GetString("FileSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File saved successfully..
        /// </summary>
        internal static string FileSaveSucceed {
            get {
                return ResourceManager.GetString("FileSaveSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string findButton {
            get {
                return ResourceManager.GetString("findButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find:.
        /// </summary>
        internal static string findLabel {
            get {
                return ResourceManager.GetString("findLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string findTabPage {
            get {
                return ResourceManager.GetString("findTabPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string formMessageBox {
            get {
                return ResourceManager.GetString("formMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string formMessageBox_btnOK {
            get {
                return ResourceManager.GetString("formMessageBox_btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details:.
        /// </summary>
        internal static string formMessageBox_lblDetails {
            get {
                return ResourceManager.GetString("formMessageBox_lblDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to detail here.
        /// </summary>
        internal static string formMessageBox_txtDetail {
            get {
                return ResourceManager.GetString("formMessageBox_txtDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message here.
        /// </summary>
        internal static string formMessageBox_txtMessage {
            get {
                return ResourceManager.GetString("formMessageBox_txtMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get current map view extent..
        /// </summary>
        internal static string GetCurrentExtentFailed {
            get {
                return ResourceManager.GetString("GetCurrentExtentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string helpTabPage {
            get {
                return ResourceManager.GetString("helpTabPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://sourceforge.net/apps/mediawiki/geoportal/index.php?title=Geoportal_CSW_Clients.
        /// </summary>
        internal static string helpUrl {
            get {
                return ResourceManager.GetString("helpUrl", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap hideAll {
            get {
                object obj = ResourceManager.GetObject("hideAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide All FootPrint.
        /// </summary>
        internal static string hideAllFootprintTooltip {
            get {
                return ResourceManager.GetString("hideAllFootprintTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Catalog:.
        /// </summary>
        internal static string inCatalogLabel {
            get {
                return ResourceManager.GetString("inCatalogLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected IMS Service already exists in map..
        /// </summary>
        internal static string LayerAlreadyInMap {
            get {
                return ResourceManager.GetString("LayerAlreadyInMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string linkLblAbt {
            get {
                return ResourceManager.GetString("linkLblAbt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSW Client for ArcGIS Help.
        /// </summary>
        internal static string linkLblHelp {
            get {
                return ResourceManager.GetString("linkLblHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Data and Maps Only.
        /// </summary>
        internal static string liveDataAndMapsOnlyCheckBox {
            get {
                return ResourceManager.GetString("liveDataAndMapsOnlyCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load catalogs..
        /// </summary>
        internal static string LoadCatalogsFailed {
            get {
                return ResourceManager.GetString("LoadCatalogsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load Configure Tab..
        /// </summary>
        internal static string LoadConfigTabFailed {
            get {
                return ResourceManager.GetString("LoadConfigTabFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load Find Services..
        /// </summary>
        internal static string LoadFindServicesFailed {
            get {
                return ResourceManager.GetString("LoadFindServicesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load help files..
        /// </summary>
        internal static string LoadHelpFilesFailed {
            get {
                return ResourceManager.GetString("LoadHelpFilesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load metadata XML..
        /// </summary>
        internal static string LoadMetadataFailed {
            get {
                return ResourceManager.GetString("LoadMetadataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load metadata formatting stylesheet..
        /// </summary>
        internal static string LoadMetadataFormattingStylesheetFailed {
            get {
                return ResourceManager.GetString("LoadMetadataFormattingStylesheetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load metadata preparation stylesheet..
        /// </summary>
        internal static string LoadMetadataPreparationStylesheetFailed {
            get {
                return ResourceManager.GetString("LoadMetadataPreparationStylesheetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load profiles..
        /// </summary>
        internal static string LoadProfilesFailed {
            get {
                return ResourceManager.GetString("LoadProfilesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Service Information not available in metadata..
        /// </summary>
        internal static string MapServiceInfoNotAvailable {
            get {
                return ResourceManager.GetString("MapServiceInfoNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected map service layer already exists in map..
        /// </summary>
        internal static string MapServiceLayerAlreadyExistInMap {
            get {
                return ResourceManager.GetString("MapServiceLayerAlreadyExistInMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum:.
        /// </summary>
        internal static string maximumLabel {
            get {
                return ResourceManager.GetString("maximumLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Metadata&gt; node missing..
        /// </summary>
        internal static string MetadataNodeMissing {
            get {
                return ResourceManager.GetString("MetadataNodeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string newCatalogToolTip {
            get {
                return ResourceManager.GetString("newCatalogToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No catalog was selected..
        /// </summary>
        internal static string NoCatalogSelected {
            get {
                return ResourceManager.GetString("NoCatalogSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found..
        /// </summary>
        internal static string NoRecordsFound {
            get {
                return ResourceManager.GetString("NoRecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No search result was selected..
        /// </summary>
        internal static string NoSearchResultSelected {
            get {
                return ResourceManager.GetString("NoSearchResultSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a map service..
        /// </summary>
        internal static string NotAMapService {
            get {
                return ResourceManager.GetString("NotAMapService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a CSW Catalog..
        /// </summary>
        internal static string PleaseSelectACswCatalog {
            get {
                return ResourceManager.GetString("PleaseSelectACswCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to prepare metadata..
        /// </summary>
        internal static string PrepareMetadataFailed {
            get {
                return ResourceManager.GetString("PrepareMetadataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string resultsLabel {
            get {
                return ResourceManager.GetString("resultsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve metadata from catalog..
        /// </summary>
        internal static string RetrieveMetadataFromCatalogFailed {
            get {
                return ResourceManager.GetString("RetrieveMetadataFromCatalogFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string saveCatalogToolTip {
            get {
                return ResourceManager.GetString("saveCatalogToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string SearchResultsLabelText {
            get {
                return ResourceManager.GetString("SearchResultsLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an item to delete..
        /// </summary>
        internal static string SelectAnItemToDelete {
            get {
                return ResourceManager.GetString("SelectAnItemToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an item to update..
        /// </summary>
        internal static string SelectAnItemToUpdate {
            get {
                return ResourceManager.GetString("SelectAnItemToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Server&gt; node missing..
        /// </summary>
        internal static string ServerNodeMissing {
            get {
                return ResourceManager.GetString("ServerNodeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service type could not be determined..
        /// </summary>
        internal static string serviceTypeUnknown {
            get {
                return ResourceManager.GetString("serviceTypeUnknown", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap showAll {
            get {
                object obj = ResourceManager.GetObject("showAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All FootPrint.
        /// </summary>
        internal static string showAllFootPrintToolTip {
            get {
                return ResourceManager.GetString("showAllFootPrintToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No spatial reference was defined for the active map view..
        /// </summary>
        internal static string SpatialReferenceNotDefined {
            get {
                return ResourceManager.GetString("SpatialReferenceNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please uncheck &quot;Use Current Extent&quot; checkbox and try again..
        /// </summary>
        internal static string UncheckCurrentExtentAndTryAgain {
            get {
                return ResourceManager.GetString("UncheckCurrentExtentAndTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown coordinate system..
        /// </summary>
        internal static string UnknownCoordinateSystem {
            get {
                return ResourceManager.GetString("UnknownCoordinateSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported coordinate system..
        /// </summary>
        internal static string UnsupportedCoordinateSystem {
            get {
                return ResourceManager.GetString("UnsupportedCoordinateSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url cannot be empty..
        /// </summary>
        internal static string UrlIsEmpty {
            get {
                return ResourceManager.GetString("UrlIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Current Extent.
        /// </summary>
        internal static string useCurrentExtentCheckBox {
            get {
                return ResourceManager.GetString("useCurrentExtentCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string VersionNo {
            get {
                return ResourceManager.GetString("VersionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Metadata.
        /// </summary>
        internal static string ViewMetadataForm {
            get {
                return ResourceManager.GetString("ViewMetadataForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Metadata.
        /// </summary>
        internal static string viewMetadataToolTip {
            get {
                return ResourceManager.GetString("viewMetadataToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string WarningMessageDialogCaption {
            get {
                return ResourceManager.GetString("WarningMessageDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WCS service with no GeoTiff interface..
        /// </summary>
        internal static string wcsWithNoGeoTiffInterface {
            get {
                return ResourceManager.GetString("wcsWithNoGeoTiffInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Files|*.xml.
        /// </summary>
        internal static string XmlFilesFilter {
            get {
                return ResourceManager.GetString("XmlFilesFilter", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap zoom_to_footprint {
            get {
                object obj = ResourceManager.GetObject("zoom_to_footprint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to Footprint.
        /// </summary>
        internal static string zoomtoFootprintToolTip {
            get {
                return ResourceManager.GetString("zoomtoFootprintToolTip", resourceCulture);
            }
        }
    }
}
