/* See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * Esri Inc. licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.esri.gpt.publish {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.esri.gpt.publish.StringMessages", typeof(StringMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESRI GIS Portal - Publish Metadata.
        /// </summary>
        internal static string ApplicationCaption {
            get {
                return ResourceManager.GetString("ApplicationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bin.
        /// </summary>
        internal static string Bin {
            get {
                return ResourceManager.GetString("Bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorMessageDialogCaption {
            get {
                return ResourceManager.GetString("ErrorMessageDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to esriGeoprocessing.GpDispatch.1.
        /// </summary>
        internal static string GpDispatchProgId {
            get {
                return ResourceManager.GetString("GpDispatchProgId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing Client.
        /// </summary>
        internal static string GPTPublishClientCaption {
            get {
                return ResourceManager.GetString("GPTPublishClientCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geoportal.
        /// </summary>
        internal static string GPTPublishClientCategory {
            get {
                return ResourceManager.GetString("GPTPublishClientCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing Client.
        /// </summary>
        internal static string GPTPublishClientCmdMsg {
            get {
                return ResourceManager.GetString("GPTPublishClientCmdMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing Client.
        /// </summary>
        internal static string GPTPublishClientToolTip {
            get {
                return ResourceManager.GetString("GPTPublishClientToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter password.
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter publish service name.
        /// </summary>
        internal static string InvalidService {
            get {
                return ResourceManager.GetString("InvalidService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter publish url.
        /// </summary>
        internal static string InvalidUrl {
            get {
                return ResourceManager.GetString("InvalidUrl", resourceCulture);
            }
        }

        /// <summary>
        ///   Metadata config directory not found.
        /// </summary>
        internal static string MetadataConfigNotFound
        {
            get
            {
                return ResourceManager.GetString("MetadataConfigNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Metadata config directory not found.
        /// </summary>
        internal static string MetadataConfigDirectoryNotFound
        {
            get
            {
                return ResourceManager.GetString("MetadataConfigDirectoryNotFound", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to Please enter username.
        /// </summary>
        internal static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to publishMetadata.log.
        /// </summary>
        internal static string LogFilePath {
            get {
                return ResourceManager.GetString("LogFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to publishButtonConfig.xml.
        /// </summary>
        internal static string PublishButtonConfigFileName {
            get {
                return ResourceManager.GetString("PublishButtonConfigFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata/Publisher/arcimsmd.xml.
        /// </summary>
        internal static string PublisherXML {
            get {
                return ResourceManager.GetString("PublisherXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to publish metadata, please check the log file at.
        /// </summary>
        internal static string PublishFailureMsg {
            get {
                return ResourceManager.GetString("PublishFailureMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish complete. Execution summary found at.
        /// </summary>
        internal static string PublishSuccessMsg {
            get {
                return ResourceManager.GetString("PublishSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        internal static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setting.
        /// </summary>
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string SuccessMessageDialogCaption {
            get {
                return ResourceManager.GetString("SuccessMessageDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbox.
        /// </summary>
        internal static string Toolbox {
            get {
                return ResourceManager.GetString("Toolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ESRI/GeoportalPublishClient/.
        /// </summary>
        internal static string ToolboxPath {
            get {
                return ResourceManager.GetString("ToolboxPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PublishMetadata.
        /// </summary>
        internal static string ToolScript {
            get {
                return ResourceManager.GetString("ToolScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string TransformXsltName
        {
            get
            {
                return ResourceManager.GetString("TransformXsltName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to userSettings.
        /// </summary>
        internal static string UserSettings
        {
            get
            {
                return ResourceManager.GetString("UserSettings", resourceCulture);
            }

        }
                
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string WarningMessageDialogCaption {
            get {
                return ResourceManager.GetString("WarningMessageDialogCaption", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to userSettings.
        /// </summary>
        internal static string PublishSuccess
        {
            get
            {
                return ResourceManager.GetString("PublicationSuccessful", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to userSettings.
        /// </summary>
        internal static string PublishFailure
        {
            get
            {
                return ResourceManager.GetString("PublicationFailure", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to userSettings.
        /// </summary>
        internal static string PublicationStartedAt
        {
            get
            {
                return ResourceManager.GetString("PublicationStartedAt", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to userSettings.
        /// </summary>
        internal static string PublicationParameters
        {
            get
            {
                return ResourceManager.GetString("PublicationParameters", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to userSettings.
        /// </summary>
        internal static string MetadataServerUrl
        {
            get
            {
                return ResourceManager.GetString("MetadataServerUrl", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to userSettings.
        /// </summary>
        internal static string ServiceName
        {
            get
            {
                return ResourceManager.GetString("ServiceName", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to userSettings.
        /// </summary>
        internal static string PublisherUsername
        {
            get
            {
                return ResourceManager.GetString("PublisherUsername", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to userSettings.
        /// </summary>
        internal static string WorkspaceName
        {
            get
            {
                return ResourceManager.GetString("WorkspaceName", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to userSettings.
        /// </summary>
        internal static string SelectedContainerCategory
        {
            get
            {
                return ResourceManager.GetString("SelectedContainerCategory", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to userSettings.
        /// </summary>
        internal static string PublishingCompletedAt
        {
            get
            {
                return ResourceManager.GetString("PublishingCompletedAt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for ErrorOnTranslation.
        /// </summary>
        internal static string ErrorOnTranslation
        {
            get
            {
                return ResourceManager.GetString("ErrorOnTranslation", resourceCulture);
            }
        }

        

        /// <summary>
        ///   Looks up a localized string for PublishingCompleted.
        /// </summary>
        internal static string PublishingCompleted
        {
            get
            {
                return ResourceManager.GetString("PublishingCompleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to userSettings.
        /// </summary>
        internal static string PublishFormTitle
        {
            get
            {
                return ResourceManager.GetString("PublishFormTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to userSettings.
        /// </summary>
        internal static string ConnectionInfoGroupBox
        {
            get
            {
                return ResourceManager.GetString("ConnectionInfoGroupBox", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to userSettings.
        /// </summary>
        internal static string ServerUrlLabel
        {
            get
            {
                return ResourceManager.GetString("ServerUrlLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to userSettings.
        /// </summary>
        internal static string MetadataServiceLabel
        {
            get
            {
                return ResourceManager.GetString("MetadataServiceLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to userSettings.
        /// </summary>
        internal static string UserNameLabel
        {
            get
            {
                return ResourceManager.GetString("UserNameLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to userSettings.
        /// </summary>
        internal static string PasswordLabel
        {
            get
            {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to userSettings.
        /// </summary>
        internal static string ExecutionSummaryChkBox
        {
            get
            {
                return ResourceManager.GetString("ExecutionSummaryChkBox", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to userSettings.
        /// </summary>
        internal static string PublishBtn
        {
            get
            {
                return ResourceManager.GetString("PublishBtn", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to userSettings.
        /// </summary>
        internal static string CloseBtn
        {
            get
            {
                return ResourceManager.GetString("CloseBtn", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to userSettings.
        /// </summary>
        internal static string ExceutionSummaryGroupBox
        {
            get
            {
                return ResourceManager.GetString("ExceutionSummaryGroupBox", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to http://webhelp.esri.com/geoportal_extension/9.3.1/ext_csw_clnts.htm.
        /// </summary>
        internal static string helpUrl
        {
            get
            {
                return ResourceManager.GetString("helpUrl", resourceCulture);
            }
        }

    
    }
}
