//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.esri.gpt.wmc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.esri.gpt.wmc.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGS Layer added to map :.
        /// </summary>
        internal static string AddAGSLayer {
            get {
                return ResourceManager.GetString("AddAGSLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adding to service list :.
        /// </summary>
        internal static string AddingServiceList {
            get {
                return ResourceManager.GetString("AddingServiceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        internal static string Colon {
            get {
                return ResourceManager.GetString("Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dont need to add service -.
        /// </summary>
        internal static string DontNeedToAddService {
            get {
                return ResourceManager.GetString("DontNeedToAddService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while trying to set spatial reference.
        /// </summary>
        internal static string ErrSpatRef {
            get {
                return ResourceManager.GetString("ErrSpatRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... exiting.
        /// </summary>
        internal static string Exiting {
            get {
                return ResourceManager.GetString("Exiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set spatial reference: unable to create the spatial reference.
        /// </summary>
        internal static string FailedSpatRef {
            get {
                return ResourceManager.GetString("FailedSpatRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://sourceforge.net/apps/mediawiki/geoportal/index.php?title=WMC_Client.
        /// </summary>
        internal static string helpUrl {
            get {
                return ResourceManager.GetString("helpUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This does not appear to be a valid WMC document..
        /// </summary>
        internal static string InvalidWMCDocument {
            get {
                return ResourceManager.GetString("InvalidWMCDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No layers can be found..
        /// </summary>
        internal static string NoLayers {
            get {
                return ResourceManager.GetString("NoLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unrecognised service type -.
        /// </summary>
        internal static string UnrecognizedServiceType {
            get {
                return ResourceManager.GetString("UnrecognizedServiceType", resourceCulture);
            }
        }
    }
}
