//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3607
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.esri.gpt.publish.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PublishForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PublishForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.esri.gpt.publish.UI.PublishForm", typeof(PublishForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Font btnClose_Font {
            get {
                object obj = ResourceManager.GetObject("btnClose.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        internal static System.Drawing.Point btnClose_Location {
            get {
                object obj = ResourceManager.GetObject("btnClose.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        internal static System.Drawing.Size btnClose_Size {
            get {
                object obj = ResourceManager.GetObject("btnClose.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        internal static int btnClose_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnClose.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string btnClose_Text {
            get {
                return ResourceManager.GetString("btnClose.Text", resourceCulture);
            }
        }
        
        internal static System.Drawing.Font btnPublish_Font {
            get {
                object obj = ResourceManager.GetObject("btnPublish.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        internal static System.Drawing.Point btnPublish_Location {
            get {
                object obj = ResourceManager.GetObject("btnPublish.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        internal static System.Drawing.Size btnPublish_Size {
            get {
                object obj = ResourceManager.GetObject("btnPublish.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        internal static int btnPublish_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnPublish.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        internal static string btnPublish_Text {
            get {
                return ResourceManager.GetString("btnPublish.Text", resourceCulture);
            }
        }
        
        internal static System.Drawing.Point displayLogsTxtBox_Location {
            get {
                object obj = ResourceManager.GetObject("displayLogsTxtBox.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        internal static System.Drawing.Size displayLogsTxtBox_Size {
            get {
                object obj = ResourceManager.GetObject("displayLogsTxtBox.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        internal static int displayLogsTxtBox_TabIndex {
            get {
                object obj = ResourceManager.GetObject("displayLogsTxtBox.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string displayLogsTxtBox_Text {
            get {
                return ResourceManager.GetString("displayLogsTxtBox.Text", resourceCulture);
            }
        }
        
        internal static System.Drawing.Font groupBox1_Font {
            get {
                object obj = ResourceManager.GetObject("groupBox1.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        internal static System.Drawing.Point groupBox1_Location {
            get {
                object obj = ResourceManager.GetObject("groupBox1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        internal static System.Drawing.Size groupBox1_Size {
            get {
                object obj = ResourceManager.GetObject("groupBox1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        internal static int groupBox1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("groupBox1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Information.
        /// </summary>
        internal static string groupBox1_Text {
            get {
                return ResourceManager.GetString("groupBox1.Text", resourceCulture);
            }
        }
        
        internal static System.Drawing.Font groupBox2_Font {
            get {
                object obj = ResourceManager.GetObject("groupBox2.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        internal static System.Drawing.Point groupBox2_Location {
            get {
                object obj = ResourceManager.GetObject("groupBox2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        internal static System.Drawing.Size groupBox2_Size {
            get {
                object obj = ResourceManager.GetObject("groupBox2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        internal static int groupBox2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("groupBox2.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Execution Summary.
        /// </summary>
        internal static string groupBox2_Text {
            get {
                return ResourceManager.GetString("groupBox2.Text", resourceCulture);
            }
        }
        
        internal static bool groupBox2_Visible {
            get {
                object obj = ResourceManager.GetObject("groupBox2.Visible", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static bool label1_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label1.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.Drawing.Font label1_Font {
            get {
                object obj = ResourceManager.GetObject("label1.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        internal static System.Drawing.Point label1_Location {
            get {
                object obj = ResourceManager.GetObject("label1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        internal static System.Drawing.Size label1_Size {
            get {
                object obj = ResourceManager.GetObject("label1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        internal static int label1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Url:.
        /// </summary>
        internal static string label1_Text {
            get {
                return ResourceManager.GetString("label1.Text", resourceCulture);
            }
        }
        
        internal static bool label2_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label2.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.Drawing.Font label2_Font {
            get {
                object obj = ResourceManager.GetObject("label2.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        internal static System.Drawing.Point label2_Location {
            get {
                object obj = ResourceManager.GetObject("label2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        internal static System.Drawing.Size label2_Size {
            get {
                object obj = ResourceManager.GetObject("label2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        internal static int label2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label2.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata Service:.
        /// </summary>
        internal static string label2_Text {
            get {
                return ResourceManager.GetString("label2.Text", resourceCulture);
            }
        }
        
        internal static bool label3_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label3.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.Drawing.Font label3_Font {
            get {
                object obj = ResourceManager.GetObject("label3.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        internal static System.Drawing.Point label3_Location {
            get {
                object obj = ResourceManager.GetObject("label3.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        internal static System.Drawing.Size label3_Size {
            get {
                object obj = ResourceManager.GetObject("label3.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        internal static int label3_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label3.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName:.
        /// </summary>
        internal static string label3_Text {
            get {
                return ResourceManager.GetString("label3.Text", resourceCulture);
            }
        }
        
        internal static bool label4_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label4.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.Drawing.Font label4_Font {
            get {
                object obj = ResourceManager.GetObject("label4.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        internal static System.Drawing.Point label4_Location {
            get {
                object obj = ResourceManager.GetObject("label4.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        internal static System.Drawing.Size label4_Size {
            get {
                object obj = ResourceManager.GetObject("label4.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        internal static int label4_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label4.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string label4_Text {
            get {
                return ResourceManager.GetString("label4.Text", resourceCulture);
            }
        }
        
        internal static bool label5_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label5.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.Drawing.Point label5_Location {
            get {
                object obj = ResourceManager.GetObject("label5.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        internal static System.Drawing.Size label5_Size {
            get {
                object obj = ResourceManager.GetObject("label5.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        internal static int label5_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label5.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        internal static bool showLogChkBox_AutoSize {
            get {
                object obj = ResourceManager.GetObject("showLogChkBox.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.Drawing.Font showLogChkBox_Font {
            get {
                object obj = ResourceManager.GetObject("showLogChkBox.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        internal static System.Drawing.Point showLogChkBox_Location {
            get {
                object obj = ResourceManager.GetObject("showLogChkBox.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        internal static System.Drawing.Size showLogChkBox_Size {
            get {
                object obj = ResourceManager.GetObject("showLogChkBox.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        internal static int showLogChkBox_TabIndex {
            get {
                object obj = ResourceManager.GetObject("showLogChkBox.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Execution Summary.
        /// </summary>
        internal static string showLogChkBox_Text {
            get {
                return ResourceManager.GetString("showLogChkBox.Text", resourceCulture);
            }
        }
        
        internal static System.Drawing.Font txtPassword_Font {
            get {
                object obj = ResourceManager.GetObject("txtPassword.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        internal static System.Drawing.Point txtPassword_Location {
            get {
                object obj = ResourceManager.GetObject("txtPassword.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        internal static System.Drawing.Size txtPassword_Size {
            get {
                object obj = ResourceManager.GetObject("txtPassword.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        internal static int txtPassword_TabIndex {
            get {
                object obj = ResourceManager.GetObject("txtPassword.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        internal static System.Drawing.Font txtServer_Font {
            get {
                object obj = ResourceManager.GetObject("txtServer.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        internal static System.Drawing.Point txtServer_Location {
            get {
                object obj = ResourceManager.GetObject("txtServer.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        internal static System.Drawing.Size txtServer_Size {
            get {
                object obj = ResourceManager.GetObject("txtServer.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        internal static int txtServer_TabIndex {
            get {
                object obj = ResourceManager.GetObject("txtServer.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        internal static System.Drawing.Font txtService_Font {
            get {
                object obj = ResourceManager.GetObject("txtService.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        internal static System.Drawing.Point txtService_Location {
            get {
                object obj = ResourceManager.GetObject("txtService.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        internal static System.Drawing.Size txtService_Size {
            get {
                object obj = ResourceManager.GetObject("txtService.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        internal static int txtService_TabIndex {
            get {
                object obj = ResourceManager.GetObject("txtService.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPT_Publish_Metadata.
        /// </summary>
        internal static string txtService_Text {
            get {
                return ResourceManager.GetString("txtService.Text", resourceCulture);
            }
        }
        
        internal static System.Drawing.Font txtUsername_Font {
            get {
                object obj = ResourceManager.GetObject("txtUsername.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        internal static System.Drawing.Point txtUsername_Location {
            get {
                object obj = ResourceManager.GetObject("txtUsername.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        internal static System.Drawing.Size txtUsername_Size {
            get {
                object obj = ResourceManager.GetObject("txtUsername.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        internal static int txtUsername_TabIndex {
            get {
                object obj = ResourceManager.GetObject("txtUsername.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
    }
}
