define({
	settings: "设置",
	layerUrl: "图层URL",
	browse: "浏览",
	queryString: "查询字符串",
	defaultValue: "默认值",
	searchLabel: "搜索标签",
	searchHint: "搜索提示",
	linkField: "链接字段",
	noneLinkField: "无",
	refreshRate: "刷新频率",
	seconds: "秒",
	zoomScale: "缩放比例尺",
	allFields: "所有字段",
	noFieldsAvailable: "无可用字段",
	displayFields: "显示字段",
	name: "名称",
	alias: "别名",
	title: "标题",
	actions: "行为",
	input: "输入",
	output: "输出",
	operationalLayerTip:"将结果保存为可操作图层"
});