/* See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * Esri Inc. licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.esri.gpt.csw {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CswResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CswResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.esri.gpt.csw.Resources.CswResources", typeof(CswResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Catalog Failed.
        /// </summary>
        internal static string addCatalogFailed {
            get {
                return ResourceManager.GetString("addCatalogFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to map failed.
        /// </summary>
        internal static string addMapFailed {
            get {
                return ResourceManager.GetString("addMapFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Build 9.3.0.52).
        /// </summary>
        internal static string buildVersion {
            get {
                return ResourceManager.GetString("buildVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog added successfully.
        /// </summary>
        internal static string catalogAdded {
            get {
                return ResourceManager.GetString("catalogAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to CSW catalog.
        /// </summary>
        internal static string catalogConnectFailed {
            get {
                return ResourceManager.GetString("catalogConnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No CSW Catalog was selected.
        /// </summary>
        internal static string catalogNotSelected {
            get {
                return ResourceManager.GetString("catalogNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSW catalog is not specified.
        /// </summary>
        internal static string catalogNotSpecified {
            get {
                return ResourceManager.GetString("catalogNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogs:.
        /// </summary>
        internal static string catalogsTxt {
            get {
                return ResourceManager.GetString("catalogsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data saved successfully.
        /// </summary>
        internal static string dataSaved {
            get {
                return ResourceManager.GetString("dataSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data saved failed.
        /// </summary>
        internal static string dataSavedFailed {
            get {
                return ResourceManager.GetString("dataSavedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete?.
        /// </summary>
        internal static string deleteConfirm {
            get {
                return ResourceManager.GetString("deleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion Failed.
        /// </summary>
        internal static string deleteFailed {
            get {
                return ResourceManager.GetString("deleteFailed", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap display_footprint {
            get {
                object obj = ResourceManager.GetObject("display_footprint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download metadata failed.
        /// </summary>
        internal static string downloadMetadataFailed {
            get {
                return ResourceManager.GetString("downloadMetadataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download to a XML file.
        /// </summary>
        internal static string downloadXMLFile {
            get {
                return ResourceManager.GetString("downloadXMLFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to IMS service.
        /// </summary>
        internal static string failedIMSservice {
            get {
                return ResourceManager.GetString("failedIMSservice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to WMS service.
        /// </summary>
        internal static string failedWMSservice {
            get {
                return ResourceManager.GetString("failedWMSservice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File saved successfully.
        /// </summary>
        internal static string fileSaved {
            get {
                return ResourceManager.GetString("fileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save file..
        /// </summary>
        internal static string fileSavedFailed {
            get {
                return ResourceManager.GetString("fileSavedFailed", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap hideAll {
            get {
                object obj = ResourceManager.GetObject("hideAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid map service information.
        /// </summary>
        internal static string invalidService {
            get {
                return ResourceManager.GetString("invalidService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer already added.
        /// </summary>
        internal static string layerAdded {
            get {
                return ResourceManager.GetString("layerAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer not added to map.
        /// </summary>
        internal static string layerNotAdded {
            get {
                return ResourceManager.GetString("layerNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No layer to add.
        /// </summary>
        internal static string layerNotFound {
            get {
                return ResourceManager.GetString("layerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No layer to remove.
        /// </summary>
        internal static string layerNotFoundToRemove {
            get {
                return ResourceManager.GetString("layerNotFoundToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No layer to zoom.
        /// </summary>
        internal static string layerNotfoundToZoom {
            get {
                return ResourceManager.GetString("layerNotfoundToZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to map failed..
        /// </summary>
        internal static string layerZoomFailed {
            get {
                return ResourceManager.GetString("layerZoomFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load catalogs from file..
        /// </summary>
        internal static string loadCatalogFailed {
            get {
                return ResourceManager.GetString("loadCatalogFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load metadata formatting stylesheet..
        /// </summary>
        internal static string loadMetadataException {
            get {
                return ResourceManager.GetString("loadMetadataException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load metadata preparation stylesheet..
        /// </summary>
        internal static string LoadMetadataPreparationStylesheetFailed {
            get {
                return ResourceManager.GetString("LoadMetadataPreparationStylesheetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load profiles from file..
        /// </summary>
        internal static string loadProfileFailed {
            get {
                return ResourceManager.GetString("loadProfileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred when loading XML..
        /// </summary>
        internal static string loadXMLException {
            get {
                return ResourceManager.GetString("loadXMLException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found.
        /// </summary>
        internal static string noRecordFound {
            get {
                return ResourceManager.GetString("noRecordFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to prepare metadata..
        /// </summary>
        internal static string PrepareMetadataFailed {
            get {
                return ResourceManager.GetString("PrepareMetadataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an item to delete.
        /// </summary>
        internal static string resultNotSelected {
            get {
                return ResourceManager.GetString("resultNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string resultTxt {
            get {
                return ResourceManager.GetString("resultTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search failed.
        /// </summary>
        internal static string searchFailed {
            get {
                return ResourceManager.GetString("searchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Search result was selected.
        /// </summary>
        internal static string searchNotSelected {
            get {
                return ResourceManager.GetString("searchNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on changing selected Index.
        /// </summary>
        internal static string selectedIndexChanged {
            get {
                return ResourceManager.GetString("selectedIndexChanged", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap showAll {
            get {
                object obj = ResourceManager.GetObject("showAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url cannot be empty.
        /// </summary>
        internal static string urlEmptyError {
            get {
                return ResourceManager.GetString("urlEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View metadata failed.
        /// </summary>
        internal static string viewMetadataFailed {
            get {
                return ResourceManager.GetString("viewMetadataFailed", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap zoom_to_footprint {
            get {
                object obj = ResourceManager.GetObject("zoom_to_footprint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to http://webhelp.esri.com/geoportal_extension/9.3.1/ext_csw_clnts.htm.
        /// </summary>
        internal static string helpUrl
        {
            get
            {
                return ResourceManager.GetString("helpUrl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for about url
        /// </summary>
        internal static string abtUrl
        {
            get
            {
                return ResourceManager.GetString("abtUrl", resourceCulture);
            }
        }
    }
}
