define({
  root: ({
    label1: "I am a demo widget.",
    label2: "This is configurable.",
    labelCatalog: "Catalog",
    selectByAttribute: "Search",
    results: "Results",
    showAll: "Show all",
    search: "Search",
    searchText: "Keywords",
    liveData: "Live Data Maps",
    clear: "Clear",
    footprints: "Footprints: ",
    show: "Show",
    hide: "Hide",
    featuresSelected: "Features found: ",
    noResults: "No results",
    queryError:"Query failed !",
    queryResult:"Query result",
    intersecting: "Intersecting",
    within: "Within",
    anywhere: "Anywhere"
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1
});
